# Generated by Django 2.0.7 on 2018-07-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.BinaryField()),
                ('total_bilirubin', models.FloatField()),
                ('direct_bilirubin', models.FloatField()),
                ('alkaline_phosphotase', models.FloatField()),
                ('alamine_aminotransferase', models.FloatField()),
                ('aspartate_aminotransferase', models.FloatField()),
                ('total_protiens', models.FloatField()),
                ('albumin', models.FloatField()),
                ('albuminGlobulin_ratio', models.FloatField()),
            ],
        ),
    ]
