# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-01 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastCancerPatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_mean', models.FloatField()),
                ('texture_mean', models.FloatField()),
                ('perimeter_mean', models.FloatField()),
                ('area_mean', models.FloatField()),
                ('smoothness_mean', models.FloatField()),
                ('compactness_mean', models.FloatField()),
                ('concavity_mean', models.FloatField()),
                ('concave_points_mean', models.FloatField()),
                ('symmetry_mean', models.FloatField()),
                ('fractal_dimension_mean', models.FloatField()),
                ('radius_se', models.FloatField()),
                ('texture_se', models.FloatField()),
                ('perimeter_se', models.FloatField()),
                ('area_se', models.FloatField()),
                ('smoothness_se', models.FloatField()),
                ('compactness_se', models.FloatField()),
                ('concavity_se', models.FloatField()),
                ('concave_points_se', models.FloatField()),
                ('symmetry_se', models.FloatField()),
                ('fractal_dimension_se', models.FloatField()),
                ('radius_worst', models.FloatField()),
                ('texture_worst', models.FloatField()),
                ('perimeter_worst', models.FloatField()),
                ('area_worst', models.FloatField()),
                ('smoothness_worst', models.FloatField()),
                ('compactness_worst', models.FloatField()),
                ('concavity_worst', models.FloatField()),
                ('concave_points_worst', models.FloatField()),
                ('symmetry_worst', models.FloatField()),
                ('fractal_dimension_worst', models.FloatField()),
                ('hasDisease', models.IntegerField()),
            ],
        ),
    ]
