# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-02 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_breastcancerpatientinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='breastcancerpatientinfo',
            name='username',
            field=models.CharField(default='abc', max_length=15),
        ),
        migrations.AddField(
            model_name='liverpatientinfo',
            name='username',
            field=models.CharField(default='abc', max_length=15),
        ),
    ]
