# Generated by Django 2.0.7 on 2018-07-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_patientinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinfo',
            old_name='total_protiens',
            new_name='total_proteins',
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
